---
http_interactions:
- request:
    method: post
    uri: https://development.avalara.net/1.0/tax/get
    body:
      encoding: UTF-8
      string: '{"DocCode":"R269040280","DocDate":"2019-03-20","Discount":"0.0","Commit":false,"DocType":"SalesOrder","Addresses":[{"AddressCode":"Orig","Line1":"915
        S Jackson St","Line2":"","City":"Montgomery","Region":"Alabama","PostalCode":"36104","Country":"United
        States"},{"AddressCode":"Dest","Line1":"915 S Jackson St","Line2":"","City":"Montgomery","Region":"Alabama","Country":"US","PostalCode":"36104"}],"Lines":[{"LineNo":"1-LI","Description":"Product
        #12 - 133","TaxCode":"PC030000","ItemCode":"SKU-14","Qty":1,"Amount":10.0,"OriginCode":"Orig","DestinationCode":"Dest","CustomerUsageType":null,"Discounted":false,"TaxIncluded":false}],"CustomerCode":1,"CompanyCode":"54321","CustomerUsageType":null,"ExemptionNo":null,"Client":"a0o33000004FH8l","ReferenceCode":"R269040280","DetailLevel":"Tax","CurrencyCode":"USD"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (darwin16.7.0 x86_64) ruby/2.5.1p57
      Authorization:
      - Basic MTEwMDExMzA5NjoxRDEzRURBMkRDQ0M3RTRB
      Content-Type:
      - application/json
      Content-Length:
      - '813'
      Host:
      - development.avalara.net
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 20 Mar 2019 16:56:51 GMT
      Content-Type:
      - text/json; charset=utf-8
      Content-Length:
      - '555'
      Connection:
      - keep-alive
      Cache-Control:
      - private
      Content-Encoding:
      - gzip
      Vary:
      - Accept-Encoding
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/In5x8tHTanpSzfKPHqUfvdr79OHO/s7ewc5HI/7iadbyF3s7uw+3d+5t7/EXb4pF3rTZYhV+9Wb300f3P320/3D8cO/h/Xv3forbVm1WHi+q9bJF610BgA+fFs3UfOw+PX2XL1ZtUS3Dj99k77JJybh4IOhTfLIz3vc/OsnK6bokzGf+l9m7gcFk754Xy7yhb76XEDnwx4uK/vpod/v5mbYwBHp5snNvhx79OJsUZdFe45u2Xuf49AkNaZbV18/zy7zEF8ezWZ03Db7jN/xBvFKMdsZEdXrwGTWSjxjtPpEImdj4InSjEedtVpR2aPTJ+/b/Kr9QmMfP8fcJkKl5xF+9xgffWddF8+Z6xXBetwBoPn2RLfjT4+fHT46/OLafG2Lu7OIj6s81TF+/OX5zmr45/r0/+iXJ9xP8X5ooFd006Qf050cPd++nr9PvZNO3TbVMX7eAql+brp4Sv+LjE52tL6ple1EtchoJPu0O6mVF7F2al+99ursTJQbhJR+d8Uzs7dzfe/DwIb7pjHN3Z/f+Luj7S5LRe+P+ZV1c4OOfe9x5Ml7lzbpszfev19Mp4frRL0n+H2sUde9KBAAA
    http_version: 
  recorded_at: Wed, 20 Mar 2019 16:56:51 GMT
- request:
    method: post
    uri: https://development.avalara.net/1.0/tax/get
    body:
      encoding: UTF-8
      string: '{"DocCode":"R269040280","DocDate":"2019-03-20","Discount":"0.0","Commit":false,"DocType":"SalesOrder","Addresses":[{"AddressCode":"Orig","Line1":"915
        S Jackson St","Line2":"","City":"Montgomery","Region":"Alabama","PostalCode":"36104","Country":"United
        States"},{"AddressCode":"Dest","Line1":"915 S Jackson St","Line2":"","City":"Montgomery","Region":"Alabama","Country":"US","PostalCode":"36104"},{"AddressCode":"2","Line1":"1600
        Pennsylvania Ave NW","Line2":null,"City":"Washington","PostalCode":"20500","Country":"US"}],"Lines":[{"LineNo":"1-LI","Description":"Product
        #12 - 133","TaxCode":"PC030000","ItemCode":"SKU-14","Qty":1,"Amount":10.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Discounted":false,"TaxIncluded":false},{"LineNo":"1-FR","ItemCode":"Avalara
        Ground","Qty":1,"Amount":5.0,"OriginCode":"2","DestinationCode":"Dest","CustomerUsageType":null,"Description":"Shipping
        Charge","TaxCode":"FR000000","Discounted":false,"TaxIncluded":false}],"CustomerCode":1,"CompanyCode":"54321","CustomerUsageType":null,"ExemptionNo":null,"Client":"a0o33000004FH8l","ReferenceCode":"R269040280","DetailLevel":"Tax","CurrencyCode":"USD"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (darwin16.7.0 x86_64) ruby/2.5.1p57
      Authorization:
      - Basic MTEwMDExMzA5NjoxRDEzRURBMkRDQ0M3RTRB
      Content-Type:
      - application/json
      Content-Length:
      - '1160'
      Host:
      - development.avalara.net
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 20 Mar 2019 16:56:52 GMT
      Content-Type:
      - text/json; charset=utf-8
      Content-Length:
      - '665'
      Connection:
      - keep-alive
      Cache-Control:
      - private
      Content-Encoding:
      - gzip
      Vary:
      - Accept-Encoding
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAEAO29B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/In5x8tGrvFmX7Uk1yz96lH70ej2d5k3z0Sj56Gk1fZq1/Onezu7D7Z1723s7+OJNscibNluswq/e7H766D79b2/8cO/B3oP9/Z/ixlWblceLar1s0Xz3vv3wadFMzccCF5+evssXq7aoluHHb7J32aRkZDwQ9Ck+2Rl/6n90kpXTdUmoz/wvs3fx0dAwzeBf7X36cGd/Z++Av6A3nhfLvKFvvpcQofDHi4r++mh3+/mZtjCvvjzZubdDj36cTYqyaK/xTVuvc3z6hMY6y+rr5/llXuKL49msVlL3B90nDoAqAfiDVzqanTGhTA8+o0by0b7+1SWF+fxp3mZFaYd2gq5qRver12jyKr9QbI6f4+/vrOuieXO94h5ftwTQfmoosLOLjwj2+6LJUF5kC252/Pz4yfEXx/icWrlP09dvjt+cpm+Of++Pfkny/eSXJCNC25+RZ6/0HYPPs1fUGz368c/qjDBHbhzpnv7VnRDz+Q9jQm6JJQNxlL/lfHw/kSZKQyc2+oHB6impDkA70cn4olq2F9Uip8Hi0+64X1akaUrz8r1Pd3eYZ7rkoI7lozOm697O/b0HDx/iGx6NeX9nd3dn9/6uDlsxwxcPd++nr9PvZNO3TbVMX7c0KDCYtjCvM3kM4t/NmnmxvGgJDXy6GXFCSPoULPHR0xP83UH84X4facJZH3ylKPEXn+7spC/z5bK5Li+zZZGlx5d5+uK7hDxm5P8BfwRG0twFAAA=
    http_version: 
  recorded_at: Wed, 20 Mar 2019 16:56:52 GMT
recorded_with: VCR 4.0.0
